language: python
python:
  - "3.4"
env:
  - DJANGO=1.8.3
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install django-celery
  - pip install coveralls
script:
  - python manage.py makemigrations 
  - python manage.py migrate
  - python manage.py test
  - coverage run manage.py test
after_success:
  - coveralls